config/routes.rb
Rails.application.routes.draw do

   root 'homes#index'

get 'typeahead/:query' => 'buyer_profile_table#typeahead'

resources :orders do 
      collection do 
  
      post :order_master_input
      get :order_master_input
      post :add_order
   
     
  
                    end
                 end

resources :homes do 
      collection do 
  
      get :admin
      get :search_status
     
  
                    end
                 end

  resources :styles do 
      collection do 
  
      post :style_master_input
      get :style_master_input
      post :add_style
      get :get_buyer_profile_lots
  
                    end
                 end

  resources :buyers do 
      collection do 

      post :buyer_all
      get  :buyer_create
  
                   end
                end

  resources :cuttings do 
      collection do 
  
      post :cutting_search
      get :search
      get :cutting_search
      post :cutting_lineman
      get :get_buyer_profile_lots
      get :cutting_show
      get :cutting_show_one
      get :get_buyer_profile_styles
      get :get_buyer_profile_colors
      get :get_buyer_profile_orderq
      get :get_buyer_profile_product_name
                    end
                 end

  resources :sewings do 
      collection do 
  
      post :sewing_search
      get :sewing_search
      post :sewing_lineman
      post :sewing_master_input
      get :get_buyer_profile_lots
      get :sewing_show_one
      get :get_buyer_profile_styles
      get :sewing_machine_input
      get :get_buyer_profile_product_name
      get :sewing_show
      post :sewing_show
                    end
                 end

                  resources :finishings do 
      collection do 
  
     post :finishing_search
      get :finishing_search
      post :finishing_lineman
      get :get_buyer_profile_lots
      get :finishing_show
      get :finishing_show_one
      get :get_buyer_profile_styles
      get :get_buyer_profile_colors
      get :get_buyer_profile_orderq
      get :get_buyer_profile_product_name
                    end
                 end

                         resources :temps do 
      collection do 
  
      post :temp_enter
     
     
  
                    end
                 end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

def admin

if params[:search].present?
	@posts = BuyerProfileTable.matching_contractNumber_or_contractDate(params[:search])
	#.page(params[:page])
  else
     @posts = BuyerProfileTable.all
   end
end

def search_status

	search_styleno = params[:style_no]
 	styleno = StyleTable.pick_some_data_one(search_styleno)

 	current_style_id = styleno[0].style_id
 	puts current_style_id.inspect

 	@postcutting = CuttingInputTable.joins('INNER JOIN buyer_profile_table ON buyer_profile_table.buyer_id = cutting_input_table.buyer_id INNER JOIN style_table ON style_table.style_id = cutting_input_table.style_id').select("style_table.style_no,style_table.order_quantity,buyer_profile_table.buying_house_name,cutting_input_table.table_no,cutting_input_table.per_hour_target,cutting_input_table.remaining_output,cutting_input_table.per_day_target,cutting_input_table.last_day_output").where("cutting_input_table.complete_status" => "Not complete" , "style_table.style_no" => params[:style_no]).to_a
  #CuttingInputTable.pick_some_data_cutting_search(current_style_id)
 	@postsewing = SewingInputTable.pick_some_data_sewing_search(current_style_id)

	 respond_to do |format|
    format.html # tablebill.html.erb
  end 

end	



#private 
   #def production_params
    # params.fetch(:homes,{}).permit(:search)
  #end 

end

app/views/homes/index.html.erb
<br><br><br>
<%= form_tag({:controller=>"homes", :action=>"search_status"},     method: :get) do %>
<!--here action is whisch page it will go  after method functionality execution -->
  <div class="center-data">Style number:
    <div class="tinput"> <%= text_field_tag(:style_no) %></div>
  </div>
  <div class="ebutton">
    <%= submit_tag "Search" %>
  </div>
<% end %>

<br><br><br><br>

<%= button_to "Order master input", order_master_input_orders_path, class: 'btn btn-sm btn-primary' %>
<br>

<br>
<%= button_to "New Style Input", style_master_input_styles_path, class: 'btn btn-sm btn-primary' %>
<br>

<br>
<%= button_to "Buyer", buyer_all_buyers_path, class: 'btn btn-sm btn-primary' %>
<br>

<br>
<%= button_to "Cutting master input", cutting_search_cuttings_path, class: 'btn btn-sm btn-primary' %>
<br>


<br>
<%= button_to "Cutting lineman", cutting_lineman_cuttings_path, class: 'btn btn-sm btn-primary' %>
<br>


<%= button_to "Sewing master input", sewing_search_sewings_path, class: 'btn btn-sm btn-primary' %>
<br>


<br>
<%= button_to "Sewings lineman", sewing_lineman_sewings_path, class: 'btn btn-sm btn-primary' %>
<br>


<br>

<%= button_to "Finishing master input", finishing_search_finishings_path, class: 'btn btn-sm btn-primary' %>
<br>

<br>
<%= button_to "Finishing lineman", finishing_lineman_finishings_path, class: 'btn btn-sm btn-primary' %>
<br>


<br>
<%= button_to "temp", temp_enter_temps_path, class: 'btn btn-sm btn-primary' %>
<br>



   

app/views/homes/search_status.html.erb
<label>SEWING STATUS</label>

<table>                         
 <tr>                          
   <th>ie_day_target</th>
    <th>hourly_target</th>
     <th>manpower</th>
          <th>total_smv</th>
      
  
 </tr>
<% @postsewing.each do |postsewing| %>      
 <tr>
   <td><%= postsewing.ie_day_target %></td>  
</br>
  <td><%= postsewing.hourly_target %></td>  
  </br>
  <td><%= postsewing.manpower %></td> 
  </br> 
  <td><%= postsewing.total_smv %></td>  
  </br>
 
 </tr>
<% end %>                     
</table>
</br>

 <label>CUTTING STATUS</label>

    <table>                         
 <tr>                          
   <th>Table number </th>
    <th>per_hour_target</th>
     
      <th>remaining_output</th>
       <th>per_day_target</th>
       <th>last_day_output</th>
<th>order_quantity</th>
          <th>buying_house_name</th>
      <th>style_no</th>
     
  
 </tr>
 
<% @postcutting.each do |postcutting| %>      
 <tr>
   <td><%= postcutting.table_no %></td>  
</br>
  <td><%= postcutting.per_hour_target %></td>  
  </br>

 
  </br>
   <td><%= postcutting.remaining_output %></td>  
</br>
 <td><%= postcutting.per_day_target %></td>  
</br>
 <td><%= postcutting.last_day_output %></td>  
</br>
<td><%= postcutting.order_quantity %></td>  
</br>
  <td><%= postcutting.buying_house_name %></td>  
</br>
  <td><%= postcutting.style_no %></td>  
  </br>
</br> 
 
 </tr>
<% end %> 
               
</table>