config/routes.rb
Rails.application.routes.draw do

   root 'homes#index'

get 'typeahead/:query' => 'buyer_profile_table#typeahead'

resources :orders do 
      collection do 
  
      post :order_master_input
      get :order_master_input
      post :add_order
   
     
  
                    end
                 end

resources :homes do 
      collection do 
  
      get :admin
      get :search_status
     
  
                    end
                 end

  resources :styles do 
      collection do 
  
      post :style_master_input
      get :style_master_input
      post :add_style
      get :get_buyer_profile_lots
  
                    end
                 end

  resources :buyers do 
      collection do 

      post :buyer_all
      get  :buyer_create
  
                   end
                end

  resources :cuttings do 
      collection do 
  
      post :cutting_search
      get :search
      get :cutting_search
      post :cutting_lineman
      get :get_buyer_profile_lots
      get :cutting_show
      get :cutting_show_one
      get :get_buyer_profile_styles
      get :get_buyer_profile_colors
      get :get_buyer_profile_orderq
      get :get_buyer_profile_product_name
                    end
                 end

  resources :sewings do 
      collection do 
  
      post :sewing_search
      get :sewing_search
      post :sewing_lineman
      post :sewing_master_input
      get :get_buyer_profile_lots
      get :sewing_show_one
      get :get_buyer_profile_styles
      get :sewing_machine_input
      get :get_buyer_profile_product_name
      get :sewing_show
      post :sewing_show
                    end
                 end

                  resources :finishings do 
      collection do 
  
     post :finishing_search
      get :finishing_search
      post :finishing_lineman
      get :get_buyer_profile_lots
      get :finishing_show
      get :finishing_show_one
      get :get_buyer_profile_styles
      get :get_buyer_profile_colors
      get :get_buyer_profile_orderq
      get :get_buyer_profile_product_name
                    end
                 end

                         resources :temps do 
      collection do 
  
      post :temp_enter
     
     
  
                    end
                 end

end

app/controllers/sewings_controller.rb
class SewingsController < ApplicationController

def sewing_search

  @buyer_profiles = BuyerProfileTable.all
  @lots = LotTable.all
  @styles = StyleTable.all
  @product_name = StyleTable.all

    buyer_id = production_params[:buyer_id]
    lot_id = production_params[:lot_id]
    style_no = production_params[:style_no]
    product_name = production_params[:product_name]
 
  unless buyer_id.nil? 
    style_id = StyleTable.where(:buyer_id => buyer_id , :lot_id => lot_id ,:style_no => style_no ,:product_name => product_name).limit(1).pluck(:style_id).first
    cookies[:buyer_id_master_cutting] = buyer_id 
    cookies[:lot_id_master_cutting] = lot_id 
    cookies[:style_id_master_cutting] = style_id 
  
  end
     

    #popuollating the  table for specific styledetails
  
    @posts = StyleTable.pick_some_data(style_id) # buyer_id parameter

    puts buyer_id.inspect
    puts lot_id.inspect
    puts style_no.inspect
    
    puts buyer_id.inspect
 
    puts product_name.inspect
    puts style_id.inspect
  

end

def sewing_show_one

  ck_a = cookies[:buyer_id_master_sewing] #buyer_id
  ck_b = cookies[:lot_id_master_sewing] #lot_id
  ck_c = cookies[:style_id_master_sewing] #style_id

   #get the order quantity for this particular style id
      orderq = StyleTable.select(:order_quantity).where(:style_id => ck_c)
      current_orderq = orderq[0].order_quantity
      ##############################################


  first_instance = SewingInputTable.new( :buyer_id => ck_a , :lot_id => ck_b, :style_id => ck_c ,:remaining_target => current_orderq)
  first_save = first_instance.save
  first_instance_id = first_instance.sewing_input_table_id

###############
  total_smv = 0
  total_manpower = 0
  
  a = params["course"]["track_codes"].length.to_i
    i = 0
      loop do
        
      current_process_name= params["course"]["track_codes"][i].to_s
      current_smv = params["course1"]["track_codes1"][i].to_s
      total_smv = params["course1"]["track_codes1"][i].to_f + total_smv
      current_target = 60/current_smv.to_f 
      current_target.round(2)
      #params["course2"]["track_codes2"][i].to_s
      current_machine_name = params["course3"]["track_codes3"][i].to_s
      current_attachment = params["course4"]["track_codes4"][i].to_s
      current_work_station = 150/current_target.to_f
      current_work_station.round(2)
      #params["course5"]["track_codes5"][i].to_s
      current_operator = params["course6"]["track_codes6"][i].to_s
      current_helper = params["course7"]["track_codes7"][i].to_s
      #total_operator = params["course6"]["track_codes6"][i].to_i + total_operator
      #puts current_operator.inspect
      total_manpower = params["course7"]["track_codes7"][i].to_i + params["course6"]["track_codes6"][i].to_i + total_manpower
      current_remark = params["course8"]["track_codes8"][i].to_s

      
      second_instance = SewingProcessDetailsTable.new( :process_name => current_process_name , :sewing_input_table_id =>  first_instance_id , :smv => current_smv , :target => current_target, :machine_name => current_machine_name, :attachment => current_attachment, :work_station => current_work_station, :operator => current_operator, :helper => current_helper , :remark => current_remark)
      second_save = second_instance.save
        i += 1
          if i >= a
            break       # this will cause execution to exit the loop
          end
        end



######################
      puts total_manpower.inspect
      puts total_smv.inspect
      ie_day_target = 600 * (total_manpower/total_smv).round(2)
      hourly_target = (ie_day_target/10).round(2)
      SewingInputTable.where('sewing_input_table_id LIKE ?', first_instance_id).update_all("manpower"  => total_manpower , "total_smv"  => total_smv , "ie_day_target"  => ie_day_target , "hourly_target"  => hourly_target)
      cookies[:ie_day_target_sewing] = ie_day_target 
      @posts =  SewingProcessDetailsTable.all.group("machine_name").select("COUNT(machine_name) AS cm,machine_name")
  


 #render :action => 'sewing_search' 
 #redirect_to sewing_search_sewings_path

  respond_to do |format|
    format.html # tablebill.html.erb 
end
end
def sewing_lineman

#@posts = CuttingInputTable.pick_some_data
#@posts = CuttingInputTable.all
#@posts = BuyerProfileTable.all

#@posts = SewingInputTable.joins('INNER JOIN buyer_profile_table ON buyer_profile_table.buyer_id = sewing_input_table.buyer_id INNER JOIN style_table ON style_table.style_id = sewing_input_table.style_id').select("style_table.style_no,style_table.order_quantity,buyer_profile_table.buying_house_name,cutting_input_table.table_no,cutting_input_table.per_hour_target,cutting_input_table.remaining_output,cutting_input_table.per_day_target,cutting_input_table.last_day_output").where("cutting_input_table.complete_status" => "Not complete" ).to_a
@posts = SewingInputTable.joins('INNER JOIN buyer_profile_table ON buyer_profile_table.buyer_id = sewing_input_table.buyer_id INNER JOIN style_table ON style_table.style_id = sewing_input_table.style_id').select("style_table.style_no,buyer_profile_table.buying_house_name,sewing_input_table.remaining_target,sewing_input_table.manpower,sewing_input_table.hourly_target,sewing_input_table.ie_day_target,sewing_input_table.remaining_target,sewing_input_table.last_day_output").where("sewing_input_table.complete_status" => "Not complete" ).to_a



  respond_to do |format|
    format.html # tablebill.html.erb
  end 

end



def sewing_show
 #params.require(:cuttings).permit(tb:[])
      #getting array length
      a = params["cuttingline"]["track_codes"].length.to_i
      #b = params["course"]["track_codes"][1].to_s
      #SewingInputTable.joins('INNER JOIN buyer_profile_table ON buyer_profile_table.buyer_id = sewing_input_table.buyer_id INNER JOIN style_table ON style_table.style_id = sewing_input_table.style_id').select("style_table.style_no,buyer_profile_table.buying_house_name,sewing_input_table.remaining_target,sewing_input_table.manpower,sewing_input_table.hourly_target,sewing_input_table.ie_day_target,sewing_input_table.remaining_target").where("sewing_input_table.complete_status" => "Not complete" ).to_a
      user = SewingInputTable.joins('INNER JOIN buyer_profile_table ON buyer_profile_table.buyer_id = sewing_input_table.buyer_id INNER JOIN style_table ON style_table.style_id = sewing_input_table.style_id').select("style_table.style_no,style_table.order_quantity,sewing_input_table.remaining_target,sewing_input_table.last_day_output,sewing_input_table.style_id,sewing_input_table.last_day_output,sewing_input_table.sewing_input_table_id").where("sewing_input_table.complete_status" => "Not complete" ).to_a

      #puts user[0].inspect
      #am = user[0].table_no
      #puts am
      ###############


      i = 0
        loop do
        current_Id = user[i].sewing_input_table_id
        c_style_id = user[i].style_id
        c_style_no = user[i].style_no
        #order_quantity = user[i].order_quantity
        prev_last_day_output = user[i].last_day_output
        current_remaining_output = user[i].remaining_target
        current_last_day_output = params["cuttingline"]["track_codes"][i].to_s
        new_remaining_output = current_remaining_output.to_i - current_last_day_output.to_i
        # puts "break"
        # puts current_Id
        #puts current_last_day_output
        #puts "break"

        #@posts = CuttingInputTable.pick_some_data_cut_line(current_Id,current_last_day_output)
        SewingInputTable.where('sewing_input_table_id LIKE ?', current_Id).update_all("last_day_output" => current_last_day_output , "remaining_target" => new_remaining_output)
        #puts params["course"]["track_codes"][i].to_s
       #check remiaing is 0?
       #checkremain = CuttingInputTable.select("remaining_output").where(:Id => current_Id)
       #check_remain = checkremain[i].remaining_output.to_i
       #if check_remain <= 0
         # CuttingInputTable.where('Id LIKE ?', current_Id).update_all("complete_status" => "Complete")
         # StyleTable.where('style_id LIKE ?', c_style_id).update_all("complete_status" => "Complete")
      # end
        
        i += 1
          if i >= a
              break       # this will cause execution to exit the loop
          end
        end
      ###########

      #puts a.inspect
      #puts d.inspect
      #puts b.inspect
      #respond_to do |format|
      #  format.html # tablebill.html.erb
      #end 
    



      render :action => 'sewing_lineman' 
      #redirect_to sewing_lineman_sewings_path 
end





  def sewing_master_input
  	#StyleTable.create!(production_params) 
  	buyer_id = production_params[:buyer_id]
  	lot_id = production_params[:lot_id]
    @posts = StyleTable.pick_some_data(buyer_id,lot_id) # buyer_id parameter



  respond_to do |format|
    format.html # tablebill.html.erb
  end 
  end
#####################################
  def sewing_machine_input
 
   ck_c = cookies[:style_id_master_sewing] #style_id
   ck_ie = cookies[:ie_day_target_sewing] # ie_day_target
  # puts ck_ie.inspect
#params.require(:cuttings).permit(tb:[])
      #getting array length
      a = params["sewingmachine"]["track_codes"].length.to_i
     # puts a
      #b = params["course"]["track_codes"][1].to_s
      machinedet=SewingProcessDetailsTable.all.group("machine_name").select("COUNT(machine_name) AS cm,machine_name")


      #puts user[0].inspect
      #am = user[0].table_no
      #puts am
      ###############

      i = 0
        loop do
        current_machine = machinedet[i].machine_name
        current_machine_total = machinedet[i].cm
        current_wise_part_one = params["sewingmachine"]["track_codes"][i].to_s
        current_wise_part_two = params["sewingmachine1"]["track_codes1"][i].to_s

app/views/sewings/sewing_lineman.html.erb
    <table>                         
 <tr>                          
   <th>hourly_target </th>
    <th>ie_day_target</th>
     <th>today's output</th>
          <th>buying_house_name</th>
      <th>style_no</th>
       <th>man power</th>
              <th>Remaining </th>
          <th>Lastday output </th>
  
 </tr>
 <%= form_for(:sewings, url: sewing_show_sewings_path, method: :post) do |f| %>
<% @posts.each do |posts| %>      
 <tr>
   <td><%= posts.hourly_target %></td>  
</br>
  <td><%= posts.ie_day_target %></td>  
  </br>
 <td><input type="textbox" name="cuttingline[track_codes][]" ...></td>
  </br>
  <td><%= posts.buying_house_name %></td>  
</br>
  <td><%= posts.style_no %></td>  
  </br>
  <td><%= posts.manpower %></td>  
   </br>
  <td><%= posts.remaining_target %></td>
    </br>
  <td><%= posts.last_day_output %></td>

</br> 
 
 </tr>
<% end %> 
 <%= f.submit "Submit" , :class => "btn btn-primary" %>       
<% end %>                 
</table>

app/views/sewings/sewing_machine_input.html.erb
<%= params["sewingmachine"]["track_codes"] %>
<%= params["sewingmachine1"]["track_codes1"] %>

app/views/sewings/sewing_search.html.erb
<div class="row">
      <div class="col s12">Dropdown Here</div>
     <%= form_for(:sewings, url: sewing_search_sewings_path, method: :post) do |f| %>

      <div class="col s6">
          <label> Buyer ID</label>
      <%= f.select :buyer_id, options_for_select(@buyer_profiles.collect{|bp| [bp.buying_house_name, bp.buyer_id]}) %>
      </div>


      <div class="col s6">
          <label> Lot ID</label>
    <%= f.select :lot_id, options_for_select(@lots.collect{|l| [l.lot_number, l.lot_id]}), {}, {"data-option-dependent" => true, "data-option-observed" => "sewings_buyer_id","data-option-url"  => "/sewings/get_buyer_profile_lots.json?buyer_id=:sewings_buyer_id", "data-option-key-method"  => :lot_id, "data-option-value-method" => :lot_number, 
      "data-option-key-method" => :lot_id, "data-option-value-method" => :lot_number,
 } %>

      </div>

    <div class="col s6">
      <label> Style ID</label>
    <%= f.select :style_no, options_for_select(@styles.collect{|s| [s.style_no, s.style_no]}), {}, {"data-option-dependent" => true, "data-option-observed" => "sewings_lot_id","data-option-url"  => "/sewings/get_buyer_profile_styles.json?lot_id=:sewings_lot_id", "data-option-key-method"  => :style_no, "data-option-value-method" => :style_no, 
      "data-option-key-method" => :style_no, "data-option-value-method" => :style_no,
 } %>
      </div>

     <div class="col s6">
      <label> Product Name</label>
    <%= f.select :product_name, options_for_select(@product_name.collect{|p| [p.product_name, p.product_name]}), {}, {"data-option-dependent" => true, "data-option-observed" => "sewings_style_no","data-option-url"  => "/sewings/get_buyer_profile_product_name.json?style_no=:sewings_style_no", "data-option-key-method"  => :product_name, "data-option-value-method" => :product_name, 
      "data-option-key-method" => :product_name, "data-option-value-method" => :product_name,
 } %>
      </div>
     
     
      <%= f.submit "Search" , :class => "btn btn-primary" %>
<% end %>


<%= form_tag({:controller=>"sewings", :action=>"sewing_search"},     method: :post) do %>
  <table>                         
 <tr>                          
   <th>Style number </th>
    <th>color</th>
     <th>Order quantity</th>
         
     </tr>

 </tr>
<% @posts.each do |posts| %>      
 <tr>
   <td><%= posts.style_no %></td>  
</br>
  <td><%= posts.color %></td>  
  </br>
  <td><%= posts.order_quantity %></td> 
  </br> 
  
 </tr>
<% end %>
</table>

<% end %>



<%= form_for(:sewings, url: sewing_show_one_sewings_path, method: :get) do |f| %>
   
           <table class="table table-bordered table-hover" id="tab_logic">
                           <thead>
                     



                   <tr >

                       <th class="text-center">
                           Process Name<br />
                       </th>
                       <th class="text-center">
                           SMV<br />
                       </th>
                       <th class="text-center">
                           Target
                       </th>
                       <th class="text-center">
                           Machine Name
                       </th>
                       <th class="text-center">
                           Attachment
                       </th>

                        <th class="text-center">
                           Work Station
                       </th>

                        <th class="text-center">
                           Operator
                       </th>

                        <th class="text-center">
                           Helper
                       </th>

                        <th class="text-center">
                           Remark
                       </th>
                     
                   </tr>
               </thead>
               
               <tbody>
            
                     
                   <tr id='addr0'>
                       
  <!--td><input type="textbox" name="cuttingline[track_codes][]" ...></td-->
   
                      <td>
                       <input type="text" name='course[track_codes][]'  placeholder='Process Name' class="form-control"/>
                       </td>
                       <td>
                       <input type="text"name='course1[track_codes1][]'  placeholder='SMV' class="form-control"/>
                       </td>
                       <td>
                       <input type="text"name='course2[track_codes2][]' placeholder='Target' class="form-control"/>
                       </td>
                       <td>
                       <input type="text" name='course3[track_codes3][]' placeholder='Machine Name' class="form-control"/>
                       </td>
                    

                      <td>
                       <input type="text"  name='course4[track_codes4][]' placeholder='Attachment' class="form-control"/>
                       </td>

                        <td>
                       <input type="text"  name='course5[track_codes5][]' placeholder='Work Station' class="form-control"/>
                       </td>

                        <td>
                       <input type="text"  name='course6[track_codes6][]' placeholder='Operator' class="form-control"/>
                       </td>

                        <td>
                       <input type="text"  name='course7[track_codes7][]' placeholder='Helper' class="form-control"/>
                       </td>

                        <td>
                       <input type="text" id="typeahead" name='course8[track_codes8][]' placeholder='Remark' class="form-control"/>
                       </td>

                   </tr>

             <%= f.submit "Submit" , :class => "btn btn-primary" %>    
              
                   <tr id='addr1'> </tr>



 </table>

<% end %>
   
 

   <a id="add_row" class="btn btn-default pull-left">Add Row</a> <a id='delete_row' class="pull-right btn btn-default">Delete Row</a>
   

<script>

var i=1;

    $("#add_row").click(function(){
     $('#addr'+i).html("<td><input name='course[track_codes][]' type='text' placeholder='Process Name' class='form-control input-md'  /></td> +</td><td><input name='course1[track_codes1][]''type='text' placeholder='SMV' class='form-control input-md' /></td><td><input  name='course2[track_codes2][]'' type='text' placeholder='Target'  class='form-control input-md'></td><td><input  name='course3[track_codes3][]' type='text' placeholder='Machine Name'  </td><td><input  name='course4[track_codes4][]' type='text' placeholder='Attachment'</td><td><input  name='course5[track_codes5][]' type='text' placeholder='Work Station'</td><td><input  name='course6[track_codes6][]' type='text' placeholder='Operator'</td><td><input  name='course7[track_codes7][]' type='text' placeholder='Helper'</td><td><input  name='course8[track_codes8][]' type='text' placeholder='Remark'</td>");

     $('#tab_logic').append('<tr id="addr'+(i+1)+'"></tr>');
;
     i++; 
 });
    $("#delete_row").click(function(){
        if(i>1){
        $("#addr"+(i-1)).html('');
        i--;
        }

    });
    
    $('select').change(function(){
     $('select').material_select(); 
 });


    </script>

app/views/sewings/sewing_show_one.html.erb
<%= params["course"]["track_codes"] %>
<%= params["course1"]["track_codes1"] %>
<%= params["course2"]["track_codes2"] %>
<%= params["course3"]["track_codes3"] %>
<%= params["course4"]["track_codes4"] %>
<%= params["course5"]["track_codes5"] %>
<%= params["course6"]["track_codes6"] %>
<%= params["course7"]["track_codes7"] %>
<%= params["course8"]["track_codes8"] %>


 <table>                         
 <tr>                          
   <th>Machine Name </th>
    <th>Total machine</th>
     <th>%Wise target</th>
        

     
  
 </tr>

 <%= form_for(:sewings, url: sewing_machine_input_sewings_path, method: :get) do |f| %>
<% @posts.each do |posts| %>      
 <tr>
   <td><%= posts.machine_name %></td>  
</br>
  <td><%= posts.cm %></td>  
  </br>
   <td><input type="textbox" name="sewingmachine[track_codes][]" ...></td>
  </br>
  <td><input type="textbox" name="sewingmachine1[track_codes1][]" ...></td>

</br> 
 
 </tr>
<% end %> 
 <%= f.submit "Submit" , :class => "btn btn-primary" %>       
<% end %>                 
</table>

 